#!/usr/bin/env python3
"""Replace OrthoFinder numerical species IDs in an IQ-TREE Newick tree.

The correspondence between numerical identifiers and proteome names is read
from the SpeciesIDs.txt file generated by OrthoFinder.
"""

import re
from pathlib import Path


SPECIES_IDS = Path(
    "references/proteomic/orthofinder/OrthoFinder/"
    "Results_orthofinder/WorkingDirectory/SpeciesIDs.txt"
)

INPUT_TREE = Path(
    "comparative_genomics/iqtree/species_tree_iqtree.treefile"
)

OUTPUT_TREE = Path(
    "comparative_genomics/iqtree/species_tree_iqtree_named.treefile"
)


def remove_fasta_extension(file_name):
    return re.sub(
        r"\.(faa|fa|fasta|fna|pep)$",
        "",
        file_name,
        flags=re.IGNORECASE,
    )


species_names = {}

for line in SPECIES_IDS.read_text(encoding="utf-8").splitlines():
    line = line.strip()

    if not line or line.startswith("#") or ":" not in line:
        continue

    numerical_id, proteome_name = line.split(":", 1)

    species_names[numerical_id.strip()] = remove_fasta_extension(
        proteome_name.strip()
    )


tree = INPUT_TREE.read_text(encoding="utf-8").strip()

for numerical_id in sorted(
    species_names,
    key=lambda value: int(value),
    reverse=True,
):
    species_name = species_names[numerical_id]

    tree = re.sub(
        rf"(?<=[(,]){re.escape(numerical_id)}(?=:)",
        species_name,
        tree,
    )


OUTPUT_TREE.write_text(
    tree + "\n",
    encoding="utf-8",
)

print(f"Named tree written to: {OUTPUT_TREE}")
