#!/usr/bin/env bash
set -euo pipefail

# Infers the maximum-likelihood species tree from the concatenated alignment
# of single-copy orthologues produced by OrthoFinder.
#
# Historical analysis:
# - IQ-TREE 3.1.2
# - automatic model selection with ModelFinder Plus
# - 1,000 ultrafast bootstrap replicates
# - automatic thread selection
#
# The numerical sequence identifiers in the resulting tree are renamed
# separately using the SpeciesIDs.txt file generated by OrthoFinder.
#
# Requirement: IQ-TREE 3.1.2.

ORTHOFINDER_RESULTS="references/proteomic/orthofinder/OrthoFinder/Results_orthofinder"
ALIGNMENT="${ORTHOFINDER_RESULTS}/WorkingDirectory/Alignments_ids/SpeciesTreeAlignment.fa"

OUTPUT_DIR="comparative_genomics/iqtree"
OUTPUT_PREFIX="${OUTPUT_DIR}/species_tree_iqtree"

mkdir -p "$OUTPUT_DIR"

iqtree3 \
    -s "$ALIGNMENT" \
    -B 1000 \
    -T AUTO \
    --prefix "$OUTPUT_PREFIX"
