#!/usr/bin/env bash
set -euo pipefail

# Applies the Action report generated by NCBI FCS-adaptor on Galaxy EU to the
# 20-kb-filtered assembly. The final screening used FCS-adaptor 0.5.0+galaxy0
# in eukaryotic mode. Its report was applied once with gx clean-genome using a
# minimum residual sequence length of 200 bp.
#
# Requirements: NCBI FCS-GX clean-genome, assembly-stats, BUSCO 6.1.0,
# Miniprot, the length-filtered assembly, the FCS-adaptor Action report, and
# the downloaded cetartiodactyla_odb10 BUSCO lineage dataset.
# Run this script from the repository root.
# Output note: files with the same names in OUTPUT_DIR and the BUSCO run are
# overwritten. Change the output directory or run name to preserve old results.

ASSEMBLY="Length_filter/final_filtered_assembly.fasta"
ADAPTOR_REPORT="FCS_adaptor/FCS_adaptor_report.tsv"
OUTPUT_DIR="FCS_adaptor"
BUSCO_DOWNLOAD_DIR="busco_downloads"

mkdir -p "$OUTPUT_DIR"

gx clean-genome \
    --input "$ASSEMBLY" \
    --action-report "$ADAPTOR_REPORT" \
    --contam-fasta-out "$OUTPUT_DIR/excluded_sequences.fasta" \
    --min-seq-len 200 \
    --output "$OUTPUT_DIR/assembly_FCS_adaptor_clean.fasta"

ADAPTOR_CLEAN_ASSEMBLY="$OUTPUT_DIR/assembly_FCS_adaptor_clean.fasta"

# Basic assembly statistics.
ASSEMBLY_FASTA="$ADAPTOR_CLEAN_ASSEMBLY" \
ASSEMBLY_STATS_OUTPUT="$OUTPUT_DIR/qc/assembly_stats/assembly_stats.txt" \
bash scripts/07_Shared_QC/assembly_stats.sh

# Genome completeness of the final cleaned contig assembly.
ASSEMBLY_FASTA="$ADAPTOR_CLEAN_ASSEMBLY" \
BUSCO_RUN_NAME="busco_post_fcs_adaptor" \
BUSCO_OUTPUT_DIR="$OUTPUT_DIR/qc/busco" \
BUSCO_DOWNLOAD_DIR="$BUSCO_DOWNLOAD_DIR" \
bash scripts/07_Shared_QC/busco/busco_genome.sh

echo "FCS-adaptor-cleaned assembly: $ADAPTOR_CLEAN_ASSEMBLY"
