#!/usr/bin/env bash
set -euo pipefail

# Identifies orthogroups and single-copy orthologues using OrthoFinder 3.1.5.
#
# Before running:
# - The selected reference proteomes must be present in:
#     references/proteomic/orthofinder/
# - The representative target-species proteome generated by the annotation
#   pipeline must also be copied into that directory.
# - Each proteome must contain one representative protein isoform per gene.
#
# Requirements: OrthoFinder 3.1.5 installed in an environment that also
# provides DIAMOND, FAMSA, and FastTree.
#
# Reusing RUN_NAME may overwrite or conflict with an existing analysis.
# Change it before rerunning if previous results must be preserved.

PROTEOMES_DIR="references/proteomic/orthofinder"
RUN_NAME="orthofinder"
THREADS=16
ALGORITHM_THREADS=4

orthofinder \
    -f "$PROTEOMES_DIR" \
    -t "$THREADS" \
    -a "$ALGORITHM_THREADS" \
    -M msa \
    -S diamond \
    -A famsa \
    -T fasttree \
    -n "$RUN_NAME"
